"""Typed radar processing facade."""

from .angle import (
    ArrayGeometry,
    BeamCube,
    beam_cube,
    conventional_steering,
    fft2_aoa,
    music_image,
    music_spectrum,
    mvdr_weights,
    phase_comparison_aoa,
    tdm_compensate,
)
from .detection import (
    Detections,
    POINT_CLOUD_COLUMNS,
    PointCloud,
    ca_cfar,
    ca_cfar_1d,
    ca_cfar_fast,
    combine_incoherent,
    os_cfar,
    point_cloud,
)
from .range_doppler import (
    RangeDopplerMap,
    RangeProfile,
    lag_axis,
    matched_filter,
    microdoppler_spectrogram,
    pulse_samples,
    range_doppler_map,
    range_profile,
)
from .signal import (
    ProcessingAxes,
    ProcessingCube,
)
from .tracking import DetectionFrame, TrackHandoff, nearest_neighbour_associator

__all__ = [
    "ArrayGeometry",
    "BeamCube",
    "DetectionFrame",
    "Detections",
    "POINT_CLOUD_COLUMNS",
    "PointCloud",
    "ProcessingAxes",
    "ProcessingCube",
    "TrackHandoff",
    "RangeDopplerMap",
    "RangeProfile",
    "beam_cube",
    "ca_cfar",
    "ca_cfar_1d",
    "ca_cfar_fast",
    "combine_incoherent",
    "conventional_steering",
    "fft2_aoa",
    "lag_axis",
    "matched_filter",
    "microdoppler_spectrogram",
    "music_image",
    "music_spectrum",
    "mvdr_weights",
    "nearest_neighbour_associator",
    "os_cfar",
    "phase_comparison_aoa",
    "point_cloud",
    "pulse_samples",
    "range_doppler_map",
    "range_profile",
    "tdm_compensate",
]
